### ISSUE TITLE
Policy on Altcoins/Altchains missinformation

### ISSUE THREAD

**Issue by peerchemist** [apoelstra/rust-bitcoin#17]
Hello,

as a final not of this project README you've linked the `A Treatise on Altcoins` by A. Poelstra as a note on altcoins in general. I must warn you that this paper while it is quite popular and readily quoted is not a prime example of unbiased and elaborate research paper on topic of cryptocurrency.
I will just warn to statement made on Peercoin, a altcoin which I help to develop and maintain.

Author states:
>  ... prototypical proof-of-stake currency, Peercoin, depends on developer signatures to determine block validity: that is, its consensus is not distributed.

Which is all but truth. If I understood the author, he states that every block on the Peercoin network must be signed by developer (Sunny King) to become valid, and thus network is not decentralized.
Which is far from truth, naturally. Each block is signed by whoever mines it or mints it.

**Comment by apoelstra** [comment]
Thanks for the bug report, but this is not the place to file bugs on the altcoin treatise. You're welcome to email me or find me on IRC as andytoshi.

Also, [these lines of code in peercoin](https://github.com/ppcoin/ppcoin/blob/master/src/main.cpp#L2008-L2010) shows that any block must match the latest "sync checkpoint", which [must have a signature from some single developer key](https://github.com/ppcoin/ppcoin/blob/master/src/checkpoints.cpp#L391-L394). You could argue that the devs don't _have_ to sign blocks, but until they do, they can [reorg them out by signing any conflict](https://github.com/ppcoin/ppcoin/blob/master/src/checkpoints.cpp#L425-L429) which is essentially the same thing.

**Comment by gmaxwell** [comment]
FWIW, it will also just stop accepting blocks if it goes too long without a signature from the developer AFAIR.

**Comment by hrobeers** [comment]
> Also, these lines of code in peercoin shows that any block must match the latest "sync checkpoint", which must have a signature from some single developer key. You could argue that the devs don't have to sign blocks, but until they do, they can reorg them out by signing any conflict which is essentially the same thing.

This is not a protocol enforced implementation, implementations can choose to ignore it. There are multiple other ways to rewrite history like the ethereum fork has shown. Checkpoints are there to ensure smooth transitions during protocol changes and they serve the stability of the coin. Peercoin does protocol innovations unlike many other alts, and these operations need mechanisms to prevent accidental forks. Yet when abuse happens nodes are free to ignore the checkpoints.

Your statements are a very narrow minded view on the truth and are the source of much misconception about Peercoin.
