### ISSUE TITLE
Deserialization usage example

### ISSUE THREAD

**Issue by maufl** [apoelstra/rust-bitcoin#20]
Hey, I would like to use this library to analyse the blockchain. I already have a downloaded copy, using the standard bitcoind. I assumed that I could use `bitcoin::network::serialize::deserialize` to deserialize a blk*.dat file into a `Block` struct. Is that correct? When I try to do that, the deserializer allocates an extremely large `Vec<u8>` and crashes because it's out of memory.

**Comment by apoelstra** [comment]
No, the blk*.dat files are not stored in the same format as blocks are in the Bitcoin network protocol. You cannot parse them with rust-bitcoin.

Thank you for reporting this memory-DoS issue though!

**Comment by maufl** [comment]
Thanks for your fast response! I'll look for another way then. If you want you can close this issue.

**Comment by apoelstra** [comment]
Fixed in https://github.com/apoelstra/rust-bitcoin/commit/cdb452f79faea376034c835557ad0cfe4ccd0659
