### ISSUE TITLE
rust-bitcoin dependency 3.10

### ISSUE THREAD

**Issue by RCasatta** [apoelstra/rust-bitcoin#23]
adding dependency
```
[dependencies]
bitcoin = "0.3"
```
In this moment cause some errors
https://gist.github.com/RCasatta/b04c778b06de02bf1f029cad6f5a7a97

(while building c4cc2a69496044e4130a4a323b7ae6e9a065162d from git works)

**Comment by apoelstra** [comment]
Can you try with `bitcoin = "0.9"`? This might break other things because the API has changed, but 0.3 was last updated with a much older version of the Rust language, so I'm not surprised that it no longer compiles.

**Comment by RCasatta** [comment]
Ehm, ops
sorry for trying a super old dependency, for some reason I thought was the last version

**Comment by apoelstra** [comment]
Ah! The README said "0.3". I fixed that :)
