### ISSUE TITLE
Forking the code

### ISSUE THREAD

**Issue by FractalMatt** [apoelstra/rust-bitcoin#24]
Hello, license makes it look like I need to get permission to fork the code?

I would like to build a blockchain in Rust for my altcoin, could I start of with this code?

Happy to provide details.

Thanks!

**Comment by frankmusher** [comment]
It's CC. You can fork it in the spirit of open source - you must share your changes so others can use them - you can't lock this up under some kind of corporate license.

**Comment by FractalMatt** [comment]
I'm of the belief that it's not truly decentralized if it's not open source and this is going to be a decentralized project.

And if course you are welcome to it, it's going to be proof of membership in a pool of accounts as part of our bigger project.

Thank you!!

**Comment by frankmusher** [comment]
I'm not the author, just translating the terms of the license into easy to understand language. CC means you can fork and use the code but you must keep the CC0 license (which means other people can also use your code). E.g. it's illegal to fork it and change it to a BSD/MIT which does not enforce this ability for others to use your improvements to the code.

**Comment by apoelstra** [comment]
The license is clearly documented in multiple places. It is **extremely immoral** for a functionally illiterate person to be creating a cryptosystem which you intend to encourage people to invest in. I strongly advise you abandon course.
