### ISSUE TITLE
Get compatible blocks

### ISSUE THREAD

**Issue by alexbirkett** [apoelstra/rust-bitcoin#26]
I want to write a program that outputs all the Bitcoin addresses that have ever been used in the Bitcoin blockchain. It does not matter if the program outputs duplicates. 

From where do I get the blocks? I note that I can't use the blockchain downloaded by Bitcoin core https://github.com/apoelstra/rust-bitcoin/issues/20 Would it be much work to support the `.dat` files? My understanding was that they are just blocks concatenated together?

**Comment by Kixunil** [comment]
I've created something similar (traverse whole Blockchain and analyze). It requires Blockchain already downloaded by Bitcoin core.

The algorithm is pretty simple: open the file and loop:

* read magic of block. If it doesn't match, break
* read block size
* seek to transactions
* iterate over transactions and de-serialize them

**Comment by alexbirkett** [comment]
Is it based on rust-bitcoin @Kixunil? Have you got a link?

**Comment by apoelstra** [comment]
Yes, it is a lot of work to track the internal data storage format of another project. Just get the blocks from the network using the Bitcoin protocol.

**Comment by Kixunil** [comment]
@alexbirkett I haven't published it yet. Maybe I'll look at it tomorrow.
