### ISSUE TITLE
Cargo build failure

### ISSUE THREAD

**Issue by josephyzhou** [apoelstra/rust-bitcoin#6]
Rust noob here, getting this error when I `cargo build`
```
aster-0.3.2/src/item.rs:210:24: 210:48 error: failed to resolve. Could not find `Constness` in `syntax::ast`
constness: ast::Constness::NotConst,
```

Dependency issue? Seems pretty low level

**Comment by apoelstra** [comment]
Yep :/. I don't think all the dependencies for this project have been building simultaneously in months. It's stalled until I get some stability.

Having said that, are you using 1.0 or the latest development rustc?

**Comment by josephyzhou** [comment]
1.1.0
